### ISSUE TITLE
Crate Notifications from multiple channels

### ISSUE THREAD

**Issue by rg9400** [widgetbot-io/crate#15]
I used to have a notification channel that pulled information from multiple different sources, and the Crate on my website served as a handy tool for users to see these notifications occur in realtime. However, because of how different all of those notifications were, I had to split them up into separate channels. Now, the Crate only listens and posts notifications from a single channel.

Would it be possible to allow Crate to listen and post notifications from a group of channels? I know you have to specify a channel when setting it up, and that's the one that initially renders, so this may be out of the scope of it, but figured I would open a FR to at least see if that could be done or even made sense.

**Comment by Yomanz** [comment]
This has been implemented
