### ISSUE TITLE
Floating Div causes issues

### ISSUE THREAD

**Issue by FoxyDev42** [widgetbot-io/crate#23]
There's a floating div created by the widget which prevents clicking anything behind it. Super inconvenient on mobile specially. 

![image](https://github.com/widgetbot-io/crate/assets/92840280/fff3014d-6efb-49af-98d0-870f9387bae0)

**Comment by mason-rogers** [comment]
I've pushed and released a fix for this (v3.5.5) if you're using the node module then you will need to update -- however if you're using a CDN (eg. the JsDelivr) link it should auto update for you.

**Comment by FoxyDev42** [comment]
Thank you!
