### ISSUE TITLE
Crate doesn't load properly sometimes

### ISSUE THREAD

**Issue by advaith1** [widgetbot-io/crate#4]
I've been having this issue recently, once in a while Crate just doesn't load and shows a tall WidgetBot embed in the bottom right corner. I see this once in a while and today one of our users reported it.
![Screenshot](https://advaith.owns-this.space/4zbgo2.png)
Also, the notification count badge shows in the top right corner of the screen.

**Comment by samdenty** [comment]
This looks to be an issue with the styling. Unless I can reproduce it, I won't be able to see what's going on / wrong.

Can you leave your browser's name + version and I'll try to reproduce it in Browser Stack

**Comment by advaith1** [comment]
I'm on Chrome 69.0.3464.0, but I don't yet know what browser the other user was using.
However, remember that this issue only occurs once in a while; most of the time it just shows normally.
