### ISSUE TITLE
On mobile, Crate always sticks to bottom right corner

### ISSUE THREAD

**Issue by advaith1** [widgetbot-io/crate#6]
When Crate detects it is being run on a mobile device, the button always sticks to the bottom right corner, but the appearance of the button changes to fit the set location.

![GIF](https://advaithbot.is-really.fun/YpfabzLoO.gif)

**Comment by samdenty** [comment]
![image](https://user-images.githubusercontent.com/13242392/41608861-63c6b004-73e1-11e8-9450-00bcbba6498f.png)

![image](https://user-images.githubusercontent.com/13242392/41608868-679ad1ba-73e1-11e8-8e90-f26c9a4da69f.png)
